
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app1'
    static_configs:
      - targets: ['app1:8000']

  - job_name: 'app2'
    static_configs:
      - targets: ['app2:8000']
      
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
