name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clone or pull latest code
          if [ ! -d "multi-app-devops" ]; then
            git clone https://github.com/Sam2op/multi-app-devops.git multi-app-devops
          fi
          cd multi-app-devops
          git reset --hard
          git pull origin main

          # Stop and rebuild containers WITHOUT cache
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
